name: null_deploy

on:
  workflow_call:
    inputs:
      release_version:
        type: string
        required: true
      unit:
        type: string
        required: true
      environment:
        type: string
        required: true
      # next_environment:
      #   type: string
      #   required: false
      deployment_statuses:
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: deploy
        run: |
          if [[ "$(echo '${{ inputs.deployment_statuses }}' |  jq --compact-output 'unique')" == '["success"]' ]]; then
            exit 0
          else
            exit 1
          fi

  # environment:
  #   if: ${{ inputs.next_environment != '' }}
  #   secrets: inherit
  #   uses: oleksandrkudin/poc-ndp-workflows/.github/workflows/update_environment.yaml@main
  #   with:
  #     unit: ${{ inputs.unit }}
  #     environment: ${{ inputs.next_environment }}
  #     release_version: ${{ inputs.release_version }}
