name: update_environment

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      unit:
        type: string
        required: true
      release_version:
        type: string
        required: true

# TODO: This must part of remote repository.
# TODO: Better management for PERSONAL_GITHUB_TOKEN
jobs:
  environment:
    name: Promote to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          repository: oleksandrkudin/poc-ndp-environments
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      
      - name: "Update env: Get deployed version"
        working-directory: environments/${{ inputs.environment }}/${{ inputs.unit }} 
        run: |
          deployed_release_version=$(jq --raw-output '.version' deploy-config.json)
          echo "deployed_release_version=$deployed_release_version" | tee -a "$GITHUB_ENV"
    
      - name: "Update env: Update version"
        working-directory: environments/${{ inputs.environment }}/${{ inputs.unit }} 
        run: |
          jq '.version = "${{ inputs.release_version }}"' deploy-config.json | tee tmp.json && mv tmp.json deploy-config.json
      
      - name: "Update env: Create PR"
        id: pull_request
        uses: peter-evans/create-pull-request@v5
        with:
          title: '[auto] ${{ inputs.environment }} :: ${{ inputs.unit }} ${{ env.deployed_release_version }} -> ${{ inputs.release_version }}'
          commit-message: '[auto] ${{ inputs.environment }} :: ${{ inputs.unit }} ${{ env.deployed_release_version }} -> ${{ inputs.release_version }}'
          branch: ${{ github.repository }}/${{ github.run_id }}/${{ github.run_attempt }}
          base: main
          add-paths: '**/deploy-config.json'
          # reviewers: '[]'
          delete-branch: true
          labels: 'automerge'
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
    
      # TODO: Private free repository does not allow auto-merge. Auto-merge should be enabled for repository.
      # TODO: Auto-merge has many prerequisites    
      # - uses: reitermarkus/automerge@v2
      #   with:
      #     merge-method: squash
      #     required-labels: automerge
      #     pull-request: ${{ steps.pull_request.outputs.pull-request-number }}
      #     # pull-request: ${{ steps.pull_request.outputs.pull-request-url }}  
      #     token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - name: "Update env: Merge PR"
        if: ${{ steps.pull_request.outputs.pull-request-number != '' }}
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          number:  ${{ steps.pull_request.outputs.pull-request-number }}
          method: squash
          repo: oleksandrkudin/poc-ndp-environments
      
      - name: "Update env: Delete branch after merge"
        if: ${{ steps.pull_request.outputs.pull-request-number != '' }}
        run: |
          git push origin --delete ${{ github.repository }}/${{ github.run_id }}/${{ github.run_attempt }}
