name: update_environment

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      unit:
        type: string
        required: true
      release_version:
        type: string
        required: true

# TODO: This must part of remote repository.
# TODO: Better management for PERSONAL_GITHUB_TOKEN
jobs:
  environment:
    name: Promote to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          repository: oleksandrkudin/poc-ndp-environments
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      
      - name: "Update env: Get deployed version"
        working-directory: environments/${{ inputs.environment }}/${{ inputs.unit }} 
        run: |
          deployed_release_version=$(jq --raw-output '.version' deploy-config.json)
          echo "deployed_release_version=$deployed_release_version" | tee -a "$GITHUB_ENV"
    
      - name: "Update env: Update version"
        working-directory: environments/${{ inputs.environment }}/${{ inputs.unit }} 
        run: |
          jq '.version = "${{ inputs.release_version }}"' deploy-config.json | tee tmp.json && mv tmp.json deploy-config.json

      - name: "Update env: Update version in nested units"
        run: |
          for version_update in $(jq --raw-output --compact-output --arg unit "${{ inputs.unit }}" '.[$unit] // [] | .[]' nested_version_updates.json); do 
            nested_unit=$(echo $version_update | jq --raw-output 'keys[0]')
            version_field=$(echo $version_update | jq --raw-output --arg nested_unit "$nested_unit"  '.[$nested_unit]')
            echo "Update $version_field in $nested_unit"
            nested_unit_config="environments/${{ inputs.environment }}/$nested_unit/deploy-config.json"
            jq --arg version_field "$version_field" '.[$version_field] = "${{ inputs.release_version }}"' $nested_unit_config | tee tmp.json && mv tmp.json $nested_unit_config
          done
      
      - uses: oleksandrkudin/poc-ndp-workflows/.github/actions/commit_changes_pr@main
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          base_branch: main
          title: '[auto-deploy] ${{ inputs.environment }} :: ${{ inputs.unit }} ${{ env.deployed_release_version }} -> ${{ inputs.release_version }}'
          add-paths: '**/deploy-config.json'
